### ISSUE TITLE
make the API simpler

### ISSUE THREAD

**Issue by zevaverbach** [LeeChunHao2000/ftx-api-wrapper-python3#4]
The method names are quite long and repetitive. How about cutting out the "public" and "private" names and maybe using the more semantically clear "create" in place of "set"?

**Comment by zevaverbach** [comment]
What do you think about replacing the `scope` argument of `_send_request` with a `PRIVATE_ENDPOINTS_LOOKUP` dictionary which that method could use when deciding which base URL to use?

**Comment by LeeChunHao2000** [comment]
I think this is a good idea

**Comment by zevaverbach** [comment]
btw I didn't remove any docstrings, I think they're quite nice

**Comment by LeeChunHao2000** [comment]
oh thanks :D

**Comment by zevaverbach** [comment]
#14 replaces the `scope` arg, and a little bonus optimization too
